CREATE TABLE IF NOT EXISTS manufacturers
(
    manufacturer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_manufacturer PRIMARY KEY (manufacturer_id)
);

CREATE TABLE IF NOT EXISTS types
(
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_type PRIMARY KEY (type_id)
);

CREATE TABLE IF NOT EXISTS characteristics
(
    characteristic_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_characteristic PRIMARY KEY (characteristic_id)
);

CREATE TABLE IF NOT EXISTS unit
(
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_unit PRIMARY KEY (unit_id)
);

CREATE TABLE IF NOT EXISTS products
(
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_serial   VARCHAR(255)                            NOT NULL,
    manufacturer_id BIGINT                                  NOT NULL,
    price           BIGINT                                  NOT NULL,
    quantity        BIGINT                                  NOT NULL,
    type_id         BIGINT                                  NOT NULL,
--    characteristic_id BIGINT NOT NULL ,
    CONSTRAINT pk_product PRIMARY KEY (product_id),
    CONSTRAINT fk_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (manufacturer_id),
    CONSTRAINT fk_type FOREIGN KEY (type_id) REFERENCES types (type_id)
);

CREATE TABLE IF NOT EXISTS products_characteristics
(
    product_id            BIGINT       NOT NULL,
    characteristic_id     BIGINT       NOT NULL,
    unit_id               BIGINT       NOT NULL,
    value_characteristics VARCHAR(512) NOT NULL,
    FOREIGN KEY (characteristic_id) REFERENCES characteristics (characteristic_id),
    FOREIGN KEY (product_id) REFERENCES products (product_id),
    FOREIGN KEY (unit_id) REFERENCES unit (unit_id)
);
